-- 코드를 입력하세요
SELECT RR.REST_ID, RI.REST_NAME,RI.FOOD_TYPE,RI.FAVORITES,RI.ADDRESS,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS RR JOIN REST_INFO AS RI ON RR.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RR.REST_ID
ORDER BY AVG(REVIEW_SCORE) DESC, RI.FAVORITES DESC;