-- 코드를 입력하세요
SELECT B.TITLE AS TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
From USED_GOODS_REPLY AS R JOIN USED_GOODS_BOARD AS B ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE <= DATE("2022-10-31")
AND B.CREATED_DATE > DATE("2022-09-30")
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC
;